epochs: 10
batch_size: 32
patience: 3
stop_epoch: 0   # 0 disables hard-stop; otherwise stop training loop at this epoch
num_workers: 4
use_amp: false
gradient_clip: 0.0

# Which split to use for "validation" during training.
# NOTE: Using "test" here leaks test information into checkpoint selection.
val_flag: val  # val | test
