name: sgd
lr: 0.01
weight_decay: 0.0
momentum: 0.9
nesterov: false
# Optional LR multiplier for slot-conditioned LayerNorm (CLN) parameters.
# When enabled, downstream training will create a separate param group for CLN (gamma/beta)
# with lr = lr * cln_lr_mult.
cln_lr_mult: 1.0
scheduler: none
min_lr: 0.0
t_max: 0
step_size: 10
gamma: 0.5
plateau_mode: min
plateau_factor: 0.5
plateau_patience: 2
plateau_threshold: 0.0001
plateau_threshold_mode: rel
plateau_cooldown: 0
plateau_min_lr: null
plateau_eps: 1.0e-08
onecycle_max_lr: null
onecycle_pct_start: 0.3
onecycle_anneal_strategy: cos
onecycle_div_factor: 25.0
onecycle_final_div_factor: 10000.0
onecycle_three_phase: false
onecycle_total_steps: 0
